[custom]
;不要随意改变关键字，否则会导致出错
;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/UnBan.list
ruleset=AI独立分流,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/AiDomain.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/CiciAi.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Developer.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Microsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Apple.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Web3.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Spotify.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Epic.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Sony.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Steam.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/YouTube.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Khan.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Edutools.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/UK.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Netflix.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/NetflixIP.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/DisneyPlus.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Bilibili.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/BilibiliHMT.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ProxyGFWlist.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Download.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=🚀 节点选择,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇮🇳 印度节点`[]🇪🇺 欧洲节点`[]🇹🇷 土耳其节点`[]🇲🇾 东南亚节点`[]🫙 自定义`.*
custom_proxy_group=AI独立分流`select`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇸🇬 新加坡节点`[]🚀 节点选择`[]🫙 自定义`.*
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇺🇲 美国手动`select`[]DIRECT`(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🫙 自定义`select`.*
custom_proxy_group=🇹🇼 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|SIN|Singapore|SEA)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(英|英国|United Kingdom|UK)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度节点`url-test`(印度|India|IN)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇪🇺 欧洲节点`url-test`(法|德|Fr|De|瑞典|Swedish|SE)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土|土耳其|Turkey|TR)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇾 东南亚节点`url-test`(马来西亚|Malaysia|MY|泰|印尼|Th)`http://www.gstatic.com/generate_204`300,,50

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
